export_file(
  name = 'Makefile.in',
  visibility = [
    '//...',
  ],
)

cxx_binary(
  name = 'date',
  header_namespace = '',
  headers = [
    'uprint.h',
  ],
  srcs = [
    'date.c',
    'uprint.c',
  ],
  deps = [
    '//:icu4c',
  ],
)
