export_file(
  name = 'Makefile.in',
  visibility = [
    '//...',
  ],
)

cxx_binary(
  name = 'cal',
  header_namespace = '',
  headers = [
    'uprint.h',
  ],
  srcs = [
    'cal.c',
    'uprint.c',
  ],
  deps = [
    '//:icu4c',
  ]
)
